name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: windows-latest  # Use windows-latest for Windows environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'

    - name: Copy .env file if not exists
      run: |
        if not exist .env (
          copy .env.example .env
        )
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generate key
      run: php artisan key:generate

    - name: Set directory permissions
      run: Icacls "storage" /grant:r "IIS_IUSRS:(OI)(CI)F /T && Icacls "bootstrap/cache" /grant:r "IIS_IUSRS:(OI)(CI)F /T

    - name: Create Database file
      run: |
        mkdir database
        type nul > database\database.sqlite

    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test
